# Importing Tensorflow version

In [3]:
%tensorflow_version 2.x

In [6]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors

In [7]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.14, tf.float64)

# Rank/Degree of Tensors

In [14]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([
                           ["test"], 
                           ["ok"]
                          ], tf.string)

In [15]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [16]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of tensors

In [13]:
rank2_tensor.shape

TensorShape([2, 2])

It tells us that there are 2 lists (first 2) and in each list there are 2 elements

In [17]:
rank2_tensor1 = tf.Variable([
                             ["Test1"],
                             ["Test2"]
                            ], tf.string)

This has rank 2 and shape as [2, 1]

In [18]:
rank2_tensor1.shape

TensorShape([2, 1])

In [19]:
rank2_tensor_3 = tf.Variable([
                              ["Test1", "Test2", "Test3"],
                              ["Ok1", "ok2", "ok3"]
], tf.string)

In [20]:
rank2_tensor_3.shape

TensorShape([2, 3])

# Changing Shape

In [23]:
# it has one list, inside that list it will have 2 lists, and in each of the 2 lists we will have 3 elements,  in this case 1
tensor1 = tf.ones([1, 2, 3]) # total elements 1*2*3 = 6
tensor2 = tf.reshape(tensor1, [2, 3, 1])
tensor3 = tf.reshape(tensor2, [3, -1]) # 3 lists and remaining elements that is 6// 3 which is 2 1's in each list

In [22]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Types of Tensors
- Variable
- Constant
- Placeholder
- Session

Only Variable is mutable others are immutable

# Evaluation tensors
- No need of Session in version 2 but we can access it through compat.v1.Session.
- we can directly use tf.function() as shown below
Difference read here
https://stackoverflow.com/questions/55142951/tensorflow-2-0-attributeerror-module-tensorflow-has-no-attribute-session

In [25]:
with tf.compat.v1.Session() as sess:
  # tensor1.eval()
  pass

In [26]:
# Using just function
msg = tf.constant('Hello, TensorFlow!')
tf.print(msg)

Hello, TensorFlow!
